name: Main

on:
  pull_request:
  push: { branches: ["main"] }
  workflow_dispatch: # Can run manually from the Actions tab

env:
  GLH_VARS_JSON: ${{ vars.GLH_VARS_JSON || secrets.GLH_VARS_JSON }}

permissions: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: git-lfs-hub/ci-cd/actions/init@main
        with: { peers: config }

      - run: |
          bun run config:vars
          bun run build
